# Generated by Django 2.2.1 on 2019-07-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textphrase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textphrasemodel',
            options={'ordering': ('slug', '-id'), 'verbose_name': 'Text Phrase', 'verbose_name_plural': 'Text Phrases'},
        ),
    ]
