# Generated by Django 2.2.1 on 2019-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymodel',
            name='language',
            field=models.CharField(db_index=True, default='global', max_length=6, verbose_name='Language'),
        ),
    ]
