# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerymodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.TagModel', verbose_name='Tags'),
        ),
    ]
