# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190709_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(help_text='235,000 T', verbose_name='Price'),
        ),
    ]
